name: "pre-release"

on:
  push:
    branches:
      - "prod"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release notes"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: fc-deployment-info
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'FRONTEND RELEASE'
          SLACK_TITLE: 'a new release has been made'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
